#!/bin/sh

mv /etc/skel/.zshrc.new /etc/skel/.zshrc
cat /etc/gdm/jovarkos-default-dconf | dconf load / 

git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
makepkg -si --noconfirm
cd ..
rm -rf yay-bin